{
    'name': 'Helpdesk',
    'version': '1.0',
    'summary': 'For great customer service',
    'description': 'Track, prioritize, and solve customer tickets',
    'category': 'Services/Helpdesk',
    'sequence': -110,
    'author': 'krishna',
    'website': '',
    'depends': ['base', 'mail','web', 'mail', 'project','contacts'],
    'data': [
                'security/ir.model.access.csv',
                'data/helpdesk_stages.xml',
                'data/tickets_tages.xml',
                'data/helpdesk_timesheet.xml',
                'wizard/helpdesk_create_timesheet.xml',
                'views/helpdesk_support_team.xml',
                # 'views/assets.xml',
                'views/my_tickets.xml',
                'views/all_tickets.xml',
                'views/female.xml',
                'views/helpdesk_stage.xml',
                'views/order_repairs.xml',
                'views/tickets_tags.xml',
                'report/watermark.xml',
                'views/menu.xml',
            ],
    'assets': {
            'web.assets_backend': [
                '/helpdesk_community/static/src/js/timer.js',
            ],
        },
    'demo': [''],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}