{
    'name': 'Employee_Management',
    'summary': 'Employee Management details',
    'description': 'its using for employee management details',
    'license': 'AGPL-3',
    'version': '15.0.0.0',
    'website': 'www.odoo.com',
    'category': 'Administration',
    'depends': ['hr', 'sale_management','mail','contacts'],
    'data': [
        'security/ir.model.access.csv',
        # 'views/employee_group.xml',
        # 'data/mail_templates.xml',
        'views/employee_details.xml',
        'views/company_details.xml',
        # 'wizard/employee_confirm.xml',
        'wizard/company_project.xml',
        'views/project_details.xml',
        'views/department_details.xml',
        'views/hr_details.xml',
        'views/leaves_details.xml',
        'views/designation_details.xml',
        'views/sales_remove.xml',
        'views/hr.xml',
        # 'data/cron.xml',
        'data/sale_cron.xml',
        # 'data/mail_templates.xml',
        # 'data/employees_report_template.xml',
        # 'data/company_report_template.xml',
        # 'data/report_actions.xml',
        'data/data.xml',
        ],
    'auto_install': False,
    'installable': True,
    'application': True
}