from . import employee_details
from . import company_details
from . import project_details
from . import department_details
from . import hr_details
from . import leaves
from . import designation_details
from . import hr
from . import sale_remove
